# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class CoffeeTable_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(792, 477)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.view = QtWidgets.QTableView(Form)
        self.view.setObjectName("view")
        self.gridLayout.addWidget(self.view, 0, 0, 1, 2)
        self.edit_btn = QtWidgets.QPushButton(Form)
        self.edit_btn.setObjectName("edit_btn")
        self.gridLayout.addWidget(self.edit_btn, 1, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Эспрессо"))
        self.edit_btn.setText(_translate("Form", "Редактировать..."))
