# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class AddEdit_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(484, 375)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.view = QtWidgets.QTableView(Form)
        self.view.setObjectName("view")
        self.gridLayout.addWidget(self.view, 0, 0, 1, 2)
        self.add_btn = QtWidgets.QPushButton(Form)
        self.add_btn.setObjectName("add_btn")
        self.gridLayout.addWidget(self.add_btn, 1, 0, 1, 1)
        self.save_btn = QtWidgets.QPushButton(Form)
        self.save_btn.setObjectName("save_btn")
        self.gridLayout.addWidget(self.save_btn, 1, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Редактирование"))
        self.add_btn.setText(_translate("Form", "Добавить строку"))
        self.save_btn.setText(_translate("Form", "Сохранить"))
